import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/Providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import Page_tansition from "@/shared/Page_tansition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Medilab HealthCare",
  description: "Generated by Medilab HealthCare",
  icons: {
    icon: "/stethoscope.png",
    shortcut: "/stethoscope.png",
    apple: "/stethoscope.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Page_tansition>
            {children}
            <Toaster position="top-right" reverseOrder={false} />
          </Page_tansition>
        </NextAuthProvider>
      </body>
    </html>
  );
}
